#!/usr/bin/env bash
# Usage: cn brain-restart
# Summary: Restart the Passenger application for brain.theclassnotes.com

set -e

ssh -p 22 classnot@theclassnotes.com -q -t "touch /home/classnot/brain.theclassnotes.com/tmp/restart.txt"
