#!/usr/bin/env bash
# Usage: cn log SUBDOMAIN
# Summary: Print last 100 lines of production log for SUBDOMAIN.theclassnotes.com

set -e

if [ $# -gt 0 ]; then
  echo "Fetching log for $1.theclassnotes.com..."
  to_execute="tail -n 100 /home/classnot/$1.theclassnotes.com/log/production.log"
  ssh -p 22 classnot@theclassnotes.com -q -t $to_execute
else
  echo "No subdomain specified."
  exit -1
fi
